### PR TITLE
Check for MySQL 5.7 and act appropriately on Redhat/Arch

### PR DESCRIPTION
**Pull request by Routhinator**
This pull request addresses issue #124 where the root password is generated randomly upon service start in MySQL 5.7+

This is addressed by requiring that the database be initialized with the new --intialize-insecure option on Arch and Redhat. This is a non-issue on Debian as debconf configures the root password before service startup.

### CODE REVIEW

**Comment by gravyboat** [comment]
Ugh, what is MySQL doing.. what a shitty problem. Thanks for putting in a fix.

**Comment by aboe76** [comment]
If I run this on an Archlinux server I get the following error:
```
[CRITICAL] Rendering SLS 'base:mysql.server' failed: Jinja variable 'pkg' is undefined
```

If I look in mysql.server.sls there isn't a reference to pkg.version should this be added to defaults.yml

**Comment by aboe76** [comment]
Tested a fix:
changed pkg.version into mysql.version

and then we can add to the defaults.yaml
version: 5.7 

tested it on archlinux where this works.

**Comment by Routhinator** [comment]
Testing on Redhat.

**Comment by Routhinator** [comment]
Still works on Redhat with this fix. Thanks for catching this. I need to setup an Arch and a Debian vagrant for testing. Generating update pull request.

**Pull request merged**
