### PR TITLE
Add better support for a config directory with split config files.

### PR DESCRIPTION
**Pull request by pprkut**
This adds optional support for having split configuration files within a config directory, most commonly /etc/my.cnf.d.

I implemented it so you can still have only one config file, if one prefers that.
Initial support added for CentOS, but it should be easy to modify other OS configurations for this.

### CODE REVIEW

**Comment by puneetk** [comment]
Is it tested for backwards compatibility on other OS'es

**Comment by pprkut** [comment]
I tried as much as I could to test myself, but I couldn't really verify on other OSes.
All the important changes are behind if checks, so it should be fine, but nonetheless I would appreciate someone testing this on an actual system other than CentOS

**Comment by gravyboat** [comment]
These look pretty good, a bit concerned since this is moving more towards the 'ng' style of formula which can be confusing to some newer users. I'd like to see what a few other people have to say prior to merging this.

**Comment by babilen** [comment]
I like it, but will have to investigate in more detail. Regardless of which I'd like to see a separate PR for all those trailing whitespace fixes as merging them is not related to this issue and something we should do either way.

**Comment by gravyboat** [comment]
Definitely agreed on the whitespace fixes.

**Comment by pprkut** [comment]
rebased against master, should now be whitespace fix free

**Pull request merged**
