### PR TITLE
Fixif

### PR DESCRIPTION
**Pull request by roock**
I think there's are two different problems during setting the root password and removing the anonymous users:

*  the elif basically matches everything because the condition is incorrect (noticed it while using arch linux. I also added support for arch linux)
* the endif is incorrectly places and thus anonymous users do not get removed on debian

I'm still a salt newbie though. 

***These changes might considerably change how the module behave!***

### CODE REVIEW

**Comment by gravyboat** [comment]
Can you resolve the conflicts? I merged your other PR and it conflicts with this one.

**Comment by ogabrielsantos** [comment]
Related: #95

**Comment by roock** [comment]
Sorry, I messed up the git repos/branches yesterday. It was already too late :). I'll close this pull request and create a new clean one

**Comment by roock** [comment]
I will need some more checking until I'll provide a new pull request. it's possible that the 2nd issue is correct, if debian by default removes the anonymous users. I'll try to dig into that in the next couple of days. Also I'm unsure about the elif, my commit would break Gentoo and FreeBSD. Maybe it should get replaced with a simple "else".

**Comment by gravyboat** [comment]
Sounds good, thanks for the update. PR when ready.

**Pull request closed without merging**
