### PR TITLE
feat(socket_authentication) Allow user to authenticate with unix_socket plugin

### PR DESCRIPTION
**Pull request by Yoda-BZH**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [x] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

None

### Describe the changes you're proposing

Allow the creation of user with the `unix_socket` plugin.

### Pillar / config required to test the proposed changes

```yml
mysql:
  user:
    myuser:
      host: localhost
      unix_socket: true
```

### Debug log showing how the proposed changes work

```yml
mysql_user_myuser_localhost:
    mysql_user.present:
      - name: myuser
      - host: 'localhost'
      - allow_passwordless: True
      - unix_socket: True
      - connection_host: 'localhost'
      - connection_user: 'root'
      - connection_pass: 'admin'
      - connection_charset: utf8
```

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [x] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by Yoda-BZH** [comment]
any update? 

or do I need to do something on my end ?

Thank you !

**Comment by javierbertoli** [comment]
Hi, @Yoda-BZH . The changes LGTM, but `commitlint` is complaining in [some of your commits messages](https://github.com/saltstack-formulas/mysql-formula/pull/246/checks?check_run_id=748918710#step:4:28) missing the [required headers for semantic versioning](https://github.com/saltstack-formulas/.github/blob/master/CONTRIBUTING.rst#linting-commit-messages-in-travis-ci). 

Mind you amend those messages (or squash your commits) and force-push, so we can merge them? Thanks!

**Comment by Yoda-BZH** [comment]
I think I fixed the commit message, but I broke the bot :s

**Comment by javierbertoli** [comment]
Hah! It's complaining on message length. 

`feat(socket_authentication): allow unix_socket authentication`

will do OK

**Comment by myii** [comment]
There you go, used @javierbertoli's suggestion to get this merged without troubling @Yoda-BZH any further!  Thanks for the contribution, that's been merged.

**Comment by Yoda-BZH** [comment]
thank you !

**Pull request merged**
