### PR TITLE
fix(server.sls): fix dictionary startswith

### PR DESCRIPTION
**Pull request by GMAzrael**
### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [x] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [X ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

#255 

### Describe the changes you're proposing

Proposed fix from code

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Review by myii — CHANGES_REQUESTED** [review]
While I understand this was taken from #255, this isn't the right fix:

* https://github.com/saltstack-formulas/mysql-formula/issues/255#issuecomment-739415243

**Review by GMAzrael — COMMENTED** [review]
Much better!

**Comment by noelmcloughlin** [comment]
Can we merge this @myii @GMAzrael

**Comment by GMAzrael** [comment]
I approve

> 
> 
> Can we merge this @myii @GMAzrael

I approve

**Pull request merged**
