### PR TITLE
refactor(jinja): improve indentation

### PR DESCRIPTION
**Pull request by ixs**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [x] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Describe the changes you're proposing

The indentation in servers.sls was unclear and made following the
control flow much harder.

Fix that by correctly indenting.

Drive-By: Change {% to {%- no-line-break opening tags for variable logic

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
@ixs  Could you fix the commit message to comply with conventional commit: https://www.conventionalcommits.org/en/v1.0.0/#summary    `git commit --amend` , etc. thanks

**Comment by noelmcloughlin** [comment]
Hi @ixs Can you do  `git commit --amend` and change to "refactor(jinja): improve indentation" and I'll merge. thanks

**Comment by ixs** [comment]
@noelmcloughlin done. Thanks for following up here.

**Comment by noelmcloughlin** [comment]
LGTM, thanks @ixs

**Pull request merged**
