### PR TITLE
Initial commit of SPM FORMULA

### PR DESCRIPTION
**Pull request by techhat**

### CODE REVIEW

**Comment by puneetk** [comment]
whats 'SPM Formula'

**Comment by techhat** [comment]
http://docs.saltstack.com/en/develop/topics/spm/

**Comment by gravyboat** [comment]
@techhat Looks cool! What's the timeline looking like for this? I assume it already works correctly in the development branch?

**Comment by techhat** [comment]
@gravyboat, it is in 2015.8.

**Comment by gravyboat** [comment]
@techhat Good to know. I didn't realize the RC had already been cut for 2015.8, thanks!

**Comment by techhat** [comment]
Yeah @gravyboat it was announced on the list this morning.

**Comment by iggy** [comment]
Burn!

**Pull request merged**
