### PR TITLE
Updated Redhat to the correct library. 

### PR DESCRIPTION
**Pull request by lmeerwood**
Added missing require to remove test database.

### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [x] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [x] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

#248

### Describe the changes you're proposing

I have updated the Redhat/CentOS family to use python3-PyMySQL now as the original library doesn't work for Python 3.

### CODE REVIEW

**Review by javierbertoli — CHANGES_REQUESTED** [review]
@lmeerwood the changes LGTM.
The pre-commit lint is failing as the commit messages don't follow the [conventions](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines) we're using now.

Would you mind changing them (ie, a `git rebase -i HEAD~2` in your branch, then choosing to `reword` the commit messages and then force push to the branch again)?

I think that something in the following lines will do

* `Updated Redhat to the correct library. Added missing require to remove test database.` ->
`fix(redhat) update python library, add missing deps`
* `Added socket to mysql calls` -> `feat(credentials) add socket access`

Thanks

**Comment by lmeerwood** [comment]
@javierbertoli yeah I can do that. Unfortunately I'm away from my main PC until Monday, so I'll do it then! Cheers.

**Comment by lmeerwood** [comment]
@javierbertoli, I have made those commit changes you requested.

**Comment by noelmcloughlin** [comment]
Fixed the conflict. Thanks, @lmeerwood and @javierbertoli

**Pull request merged**
