### PR TITLE
fix(osfamilymap.yaml): Update SUSE defaults

### PR DESCRIPTION
**Pull request by miska**
* there is no python2 in last stable releases and socket was moved as well

### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [X] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Describe the changes you're proposing

Updated requirements and configuration for SUSE

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by myii** [comment]
@miska Thanks for this PR.  It's always helpful to provide upstream references if possible.  I've linked the package below:

* https://opensuse.pkgs.org/15.1/opensuse-oss-x86_64/python3-PyMySQL-0.7.11-lp151.2.2.noarch.rpm.html

Do you mind giving a reference for the socket?

Otherwise, this looks good and thanks for fixing the commit message!

**Comment by myii** [comment]
@miska Note, it's always advantageous to use a separate branch (other than `master`, i.e. a [feature branch](https://guides.github.com/introduction/flow/)) for submitting PRs.  Otherwise, it can block the use of the `master` branch in your own fork, since whatever you do there will update this PR here (usually not desirable).  Especially for PRs that take some time to get reviewed and merged.

**Comment by miska** [comment]
Socket comes from line 384 in https://build.opensuse.org/package/view_file/openSUSE:Leap:15.1:Update/mariadb/mariadb.spec?expand=1 and 
https://en.opensuse.org/openSUSE:Packaging_Conventions_RPM_Macros#.25_rundir

**Comment by myii** [comment]
@miska Merged, thanks for clarifying things.

**Pull request merged**
